"""updatte user

Revision ID: 2b94d7f28404
Revises: c5f8309dc75f
Create Date: 2025-12-01 12:36:04.596748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b94d7f28404'
down_revision = 'c5f8309dc75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('staff_permissions', schema=None) as batch_op:
        batch_op.drop_column('expiry')

    # ### end Alembic commands ###
