"""update voucher

Revision ID: 786d9f522b01
Revises: fc9273242492
Create Date: 2025-12-10 02:32:56.706797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '786d9f522b01'
down_revision = 'fc9273242492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voucher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.Enum('GLOBAL', 'SERVICE', 'HIDDEN', name='voucherscope'), server_default='hidden', nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENT', 'FIXED', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.DECIMAL(precision=12, scale=0), nullable=False),
    sa.Column('max_discount_amount', sa.DECIMAL(precision=12, scale=0), nullable=True),
    sa.Column('min_order_value', sa.DECIMAL(precision=12, scale=0), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), server_default='0', nullable=True),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('limit_per_user', sa.Integer(), server_default='1', nullable=True),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voucher_code'), ['code'], unique=True)

    op.create_table('voucher_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.DECIMAL(precision=12, scale=0), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['voucher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'AWAITING_PAYMENT', 'CONFIRMED', 'COMPLETED', 'CANCELED', 'NO_SHOW'),
               server_default='pending',
               existing_nullable=False)
        batch_op.alter_column('total_amount',
               existing_type=mysql.FLOAT(),
               server_default='0.0',
               existing_nullable=False)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('booking_detail', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               server_default='0.0',
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('membership_tier',
               existing_type=mysql.ENUM('STANDARD', 'SILVER', 'GOLD', 'PLATINUM'),
               server_default='standard',
               existing_nullable=False)
        batch_op.alter_column('total_spent',
               existing_type=mysql.FLOAT(),
               server_default='0',
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('PAYMENT', 'REFUND'),
               server_default='payment',
               existing_nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=mysql.ENUM('CASH', 'BANK_TRANSFER'),
               server_default='cash',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'PAID', 'FAILED', 'CANCELED'),
               server_default='pending',
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('DEFAULT', 'CUSTOMER', 'STAFF', 'ADMIN'),
               server_default='default',
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('SINGLE', 'COMBO'),
               server_default='single',
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('service_badge', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('service_detail', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('staff_calendar', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('staff_permissions', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('user_auth_method', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('CUSTOMER', 'STAFF', 'ADMIN'),
               server_default='customer',
               existing_nullable=True)
        batch_op.alter_column('last_login_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_auth_method', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('last_login_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('CUSTOMER', 'STAFF', 'ADMIN'),
               server_default=sa.text("'CUSTOMER'"),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('staff_permissions', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('staff_calendar', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('service_detail', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('service_badge', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('SINGLE', 'COMBO'),
               server_default=sa.text("'SINGLE'"),
               existing_nullable=True)

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('DEFAULT', 'CUSTOMER', 'STAFF', 'ADMIN'),
               server_default=sa.text("'DEFAULT'"),
               existing_nullable=True)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'PAID', 'FAILED', 'CANCELED'),
               server_default=sa.text("'PENDING'"),
               existing_nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=mysql.ENUM('CASH', 'BANK_TRANSFER'),
               server_default=sa.text("'CASH'"),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('PAYMENT', 'REFUND'),
               server_default=sa.text("'PAYMENT'"),
               existing_nullable=False)

    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('total_spent',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=True)
        batch_op.alter_column('membership_tier',
               existing_type=mysql.ENUM('STANDARD', 'SILVER', 'GOLD', 'PLATINUM'),
               server_default=sa.text("'STANDARD'"),
               existing_nullable=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('booking_detail', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'AWAITING_PAYMENT', 'CONFIRMED', 'COMPLETED', 'CANCELED', 'NO_SHOW'),
               server_default=sa.text("'PENDING'"),
               existing_nullable=False)

    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    op.drop_table('voucher_usage')
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voucher_code'))

    op.drop_table('voucher')
    # ### end Alembic commands ###
