"""update customer booking

Revision ID: cc50430432fb
Revises: 397b845cc34a
Create Date: 2025-12-09 22:14:30.692285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc50430432fb'
down_revision = '397b845cc34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_code', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('booking_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AWAITING_PAYMENT', 'CONFIRMED', 'COMPLETED', 'CANCELED', 'NO_SHOW', name='bookingstatus'), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_code')
    )
    op.create_table('booking_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['booking_detail.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('membership_tier',
               existing_type=mysql.ENUM('STANDARD', 'SILVER', 'GOLD', 'PLATINUM'),
               server_default='standard',
               existing_nullable=False)
        batch_op.alter_column('total_spent',
               existing_type=mysql.FLOAT(),
               server_default='0',
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('DEFAULT', 'CUSTOMER', 'STAFF', 'ADMIN'),
               server_default='default',
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('SINGLE', 'COMBO'),
               server_default='single',
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('service_badge', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('service_detail', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('staff_calendar', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('staff_permissions', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('user_auth_method', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('CUSTOMER', 'STAFF', 'ADMIN'),
               server_default='customer',
               existing_nullable=True)
        batch_op.alter_column('last_login_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_auth_method', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('last_login_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('CUSTOMER', 'STAFF', 'ADMIN'),
               server_default=sa.text("'CUSTOMER'"),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('staff_permissions', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('staff_calendar', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('service_detail', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('service_badge', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('SINGLE', 'COMBO'),
               server_default=sa.text("'SINGLE'"),
               existing_nullable=True)

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('DEFAULT', 'CUSTOMER', 'STAFF', 'ADMIN'),
               server_default=sa.text("'DEFAULT'"),
               existing_nullable=True)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('total_spent',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=True)
        batch_op.alter_column('membership_tier',
               existing_type=mysql.ENUM('STANDARD', 'SILVER', 'GOLD', 'PLATINUM'),
               server_default=sa.text("'STANDARD'"),
               existing_nullable=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('update_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    op.drop_table('booking_detail')
    op.drop_table('booking')
    # ### end Alembic commands ###
